### PR TITLE
Hazard Report Setup

### PR DESCRIPTION
**Pull request by amansharma96**
Hazard Report Setup

### CODE REVIEW

**Review by shunt161 — CHANGES_REQUESTED** [review]
You have changes to App.js that are causing tests to fail. Make sure you pull develop so the correct version is in your PR

**Review by clhughe9 — CHANGES_REQUESTED** [review]
Looks like there are some lint warnings about unused items being imported if you wouldn't mind fixing those, everything else looks good.

**Comment by amansharma96** [comment]
> Looks like there are some lint warnings about unused items being imported if you wouldn't mind fixing those, everything else looks good.

I fixed it, please have a look.

**Review by shunt161 — APPROVED** [review]

**Comment by amansharma96** [comment]
> You have changes to App.js that are causing tests to fail. Make sure you pull develop so the correct version is in your PR

I made changes, please have a look and approve the request.

**Review by clhughe9 — APPROVED** [review]
Looks good to me.

**Pull request merged**
